/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSellRouteImport } from './routes/_app.sell'
import { Route as AppRevenueRouteImport } from './routes/_app.revenue'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCreditRouteImport } from './routes/_app.credit'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as AppBillsRouteImport } from './routes/_app.bills'
import { Route as AppBillsIndexRouteImport } from './routes/_app.bills.index'
import { Route as AppInventoryIdRouteImport } from './routes/_app.inventory_.$id'
import { Route as AppBillsIdRouteImport } from './routes/_app.bills.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditRoute = AppCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIndexRoute = AppBillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillsRoute,
} as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/inventory_/$id',
  path: '/inventory/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIdRoute = AppBillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/bills': typeof AppBillsRouteWithChildren
  '/cart': typeof AppCartRoute
  '/credit': typeof AppCreditRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/revenue': typeof AppRevenueRoute
  '/sell': typeof AppSellRoute
  '/settings': typeof AppSettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/bills/$id': typeof AppBillsIdRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/bills/': typeof AppBillsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/cart': typeof AppCartRoute
  '/credit': typeof AppCreditRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/revenue': typeof AppRevenueRoute
  '/sell': typeof AppSellRoute
  '/settings': typeof AppSettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof AppIndexRoute
  '/bills/$id': typeof AppBillsIdRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/bills': typeof AppBillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/bills': typeof AppBillsRouteWithChildren
  '/_app/cart': typeof AppCartRoute
  '/_app/credit': typeof AppCreditRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/revenue': typeof AppRevenueRoute
  '/_app/sell': typeof AppSellRoute
  '/_app/settings': typeof AppSettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/bills/$id': typeof AppBillsIdRoute
  '/_app/inventory_/$id': typeof AppInventoryIdRoute
  '/_app/bills/': typeof AppBillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/bills'
    | '/cart'
    | '/credit'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/revenue'
    | '/sell'
    | '/settings'
    | '/admin/dashboard'
    | '/admin/users'
    | '/bills/$id'
    | '/inventory/$id'
    | '/bills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/cart'
    | '/credit'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/revenue'
    | '/sell'
    | '/settings'
    | '/admin/dashboard'
    | '/admin/users'
    | '/'
    | '/bills/$id'
    | '/inventory/$id'
    | '/bills'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_app/bills'
    | '/_app/cart'
    | '/_app/credit'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/revenue'
    | '/_app/sell'
    | '/_app/settings'
    | '/admin/dashboard'
    | '/admin/users'
    | '/_app/'
    | '/_app/bills/$id'
    | '/_app/inventory_/$id'
    | '/_app/bills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sell': {
      id: '/_app/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revenue': {
      id: '/_app/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit': {
      id: '/_app/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof AppCreditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/': {
      id: '/_app/bills/'
      path: '/'
      fullPath: '/bills/'
      preLoaderRoute: typeof AppBillsIndexRouteImport
      parentRoute: typeof AppBillsRoute
    }
    '/_app/inventory_/$id': {
      id: '/_app/inventory_/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/$id': {
      id: '/_app/bills/$id'
      path: '/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof AppBillsIdRouteImport
      parentRoute: typeof AppBillsRoute
    }
  }
}

interface AppBillsRouteChildren {
  AppBillsIdRoute: typeof AppBillsIdRoute
  AppBillsIndexRoute: typeof AppBillsIndexRoute
}

const AppBillsRouteChildren: AppBillsRouteChildren = {
  AppBillsIdRoute: AppBillsIdRoute,
  AppBillsIndexRoute: AppBillsIndexRoute,
}

const AppBillsRouteWithChildren = AppBillsRoute._addFileChildren(
  AppBillsRouteChildren,
)

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRouteWithChildren
  AppCartRoute: typeof AppCartRoute
  AppCreditRoute: typeof AppCreditRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppSellRoute: typeof AppSellRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInventoryIdRoute: typeof AppInventoryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRouteWithChildren,
  AppCartRoute: AppCartRoute,
  AppCreditRoute: AppCreditRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppSellRoute: AppSellRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInventoryIdRoute: AppInventoryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
